Dockerfile
build.gradle
config/owasp/suppressions.xml

[RIA-2688](https://tools.hmcts.net/jira/browse/RIA-2688)
Docker file
```
[ ] Yes
[x] No
```

Docker file

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
build.gradle
charts/ia-timed-event-service/Chart.yaml
charts/ia-timed-event-service/requirements.yaml
charts/ia-timed-event-service/values.aat.template.yaml
charts/ia-timed-event-service/values.preview.template.yaml
charts/ia-timed-event-service/values.yaml
lib/AI-Agent.xml
src/functionalTest/java/uk/gov/hmcts/reform/timedevent/WelcomeFunctionTest.java
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml
src/smokeTest/java/uk/gov/hmcts/reform/timedevent/SmokeTest.java

[RIA-2688](https://tools.hmcts.net/jira/browse/RIA-2688)
AI Agent settings
```
[ ] Yes
[x] No
```

AKS preview settings + smoke test + welcome functional test

---

build.gradle
config/owasp/suppressions.xml

N/A
suppress log4j vulnerability
```
[ ] Yes
[x] No
```

suppress log4j vulnerability

---

build.gradle
charts/ia-timed-event-service/Chart.yaml
charts/ia-timed-event-service/values.preview.template.yaml
charts/ia-timed-event-service/values.yaml
src/functionalTest/java/uk/gov/hmcts/reform/timedevent/support/TokenFunctionTest.java
src/functionalTest/java/uk/gov/hmcts/reform/timedevent/testutils/FunctionalTest.java
src/integrationTest/java/uk/gov/hmcts/reform/timedevent/infrastructure/controllers/support/GetTokenIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/timedevent/testutils/SpringBootIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/timedevent/Application.java
src/main/java/uk/gov/hmcts/reform/timedevent/infrastructure/clients/IdamApi.java
src/main/java/uk/gov/hmcts/reform/timedevent/infrastructure/clients/model/IdamToken.java
src/main/java/uk/gov/hmcts/reform/timedevent/infrastructure/clients/model/IdamUserInfo.java
src/main/java/uk/gov/hmcts/reform/timedevent/infrastructure/config/FeignConfiguration.java
src/main/java/uk/gov/hmcts/reform/timedevent/infrastructure/config/HealthCheckConfiguration.java
src/main/java/uk/gov/hmcts/reform/timedevent/infrastructure/controllers/TestingSupportController.java
src/main/java/uk/gov/hmcts/reform/timedevent/infrastructure/health/DownStreamHealthIndicator.java
src/main/java/uk/gov/hmcts/reform/timedevent/infrastructure/health/ServiceHealthIndicator.java
src/main/java/uk/gov/hmcts/reform/timedevent/infrastructure/security/SystemTokenGenerator.java
src/main/java/uk/gov/hmcts/reform/timedevent/infrastructure/security/oauth2/IdamAuthoritiesConverter.java
src/main/java/uk/gov/hmcts/reform/timedevent/infrastructure/security/oauth2/IdamSystemTokenGenerator.java
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml
src/test/java/uk/gov/hmcts/reform/timedevent/infrastructure/controllers/TestingSupportControllerTest.java
src/test/java/uk/gov/hmcts/reform/timedevent/infrastructure/health/DownStreamHealthIndicatorTest.java
src/test/java/uk/gov/hmcts/reform/timedevent/infrastructure/health/ServiceHealthIndicatorTest.java
src/test/java/uk/gov/hmcts/reform/timedevent/infrastructure/security/oauth2/IdamAuthoritiesConverterTest.java
src/test/java/uk/gov/hmcts/reform/timedevent/infrastructure/security/oauth2/IdamSystemTokenGeneratorTest.java

[RIA-2687](https://tools.hmcts.net/jira/browse/RIA-2687)
system user
```
[ ] Yes
[x] No
```

Ria 2687 system user

---

infrastructure/main.tf

RIA-2689
terraform script
```
[ ] Yes
[x] No
```

RIA-2689 terraform script

---

infrastructure/variables.tf

[RIA-2689](https://tools.hmcts.net/jira/browse/RIA-2689)
terraform script 2
```
[ ] Yes
[x] No
```

RIA-2689 terraform script 2

---

charts/ia-timed-event-service/Chart.yaml
charts/ia-timed-event-service/values.yaml
infrastructure/variables.tf

[RIA-2689](https://tools.hmcts.net/jira/browse/RIA-2689)
user name fix
```
[ ] Yes
[x] No
```

RIA-2689 user name fix

---

README.md
audit.json
build.gradle

RIA-2692
Nightly build and ReadMe
```
[ ] Yes
[x] No
```

RIA-2692 Nightly build and ReadMe

---

build.gradle
src/main/java/uk/gov/hmcts/reform/timedevent/infrastructure/health/SystemUserHealthIndicator.java
src/test/java/uk/gov/hmcts/reform/timedevent/infrastructure/health/SystemUserHealthIndicatorTest.java

N/A
system user health check
```
[ ] Yes
[x] No
```

system user health check

---

build.gradle
config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/reform/timedevent/scenarios/RequestHearingRequirementsFunctionTest.java
src/integrationTest/java/uk/gov/hmcts/reform/timedevent/testutils/WithIdamStub.java
src/main/java/uk/gov/hmcts/reform/timedevent/infrastructure/clients/IdamApi.java

N/A
remove idam header + functional test fix
```
[ ] Yes
[x] No
```

remove idam header + functional test fix

---

.travis.yml
Dockerfile
build.gradle

[RIA-3446](https://tools.hmcts.net/jira/browse/RIA-3446)
```
[x] Yes
[ ] No
```

RIA-3446 upgrading to Java11

---

build.gradle

N/A
fix mutation tests for Java 11
```
[ ] Yes
[x] No
```

fix mutation tests for Java 11

---

src/main/java/uk/gov/hmcts/reform/timedevent/infrastructure/health/ServiceHealthIndicator.java

N/A
fix Sonar checks
```
[ ] Yes
[x] No
```

fix Sonar checks

---

charts/ia-timed-event-service/Chart.yaml
charts/ia-timed-event-service/values.yaml
infrastructure/main.tf
src/main/java/uk/gov/hmcts/reform/timedevent/infrastructure/services/quartz/QuartzSchedulerService.java

[RIA-3526](https://tools.hmcts.net/jira/browse/RIA-3526)
postgresql infra script
```
[ ] Yes
[x] No
```

postgresql infra script

---

charts/ia-timed-event-service/Chart.yaml
charts/ia-timed-event-service/values.yaml
infrastructure/main.tf

N/A
fix infra name
```
[ ] Yes
[x] No
```

fix infra name

---

charts/ia-timed-event-service/Chart.yaml
charts/ia-timed-event-service/values.yaml
src/main/resources/bootstrap.yaml

[RIA-3526](https://tools.hmcts.net/jira/browse/RIA-3526)
postgresql migration to version 11
```
[ ] Yes
[x] No
```

postgresql migration to version 11

---

infrastructure/main.tf
infrastructure/variables.tf

RIA-3668 Azure upgrade v2.x
Azure upgrade v2.x
```
[ ] Yes
[x] No
```

Azure upgrade v2.x

---

charts/ia-timed-event-service/Chart.yaml
charts/ia-timed-event-service/values.yaml
config/owasp/suppressions.xml
infrastructure/main.tf

RIA-3495-Remove Postgres v10 database
https://tools.hmcts.net/jira/browse/RIA-3495
```
[ ] Yes
[ x] No
```

RIA-3495-Remove Postgres v10 database

---

build.gradle
config/owasp/suppressions.xml
src/functionalTest/resources/templates/minimal-appeal-started.json

N/A
fixing security vulnerabilities
```
[ ] Yes
[x] No
```

fixing security vulnerabilities

---

src/main/java/uk/gov/hmcts/reform/timedevent/infrastructure/clients/model/idam/UserInfo.java

N/A
add more flexible model
```
[ ] Yes
[x] No
```

add more flexible model

---

config/owasp/suppressions.xml

[RIA-3961](https://tools.hmcts.net/jira/browse/RIA-3961)
```
[ ] Yes
[x] No
```

RIA3961 Investigate suppressed CVE checks

---

charts/ia-timed-event-service/Chart.yaml

[RIA-3710](https://tools.hmcts.net/jira/browse/RIA-3710)
```
[ ] Yes
[x] No
```

RIA-3710 Migrate to Helm charts v2

---

build.gradle
config/owasp/suppressions.xml

[RIA-4056](https://tools.hmcts.net/jira/browse/RIA-4056)
```
[ ] Yes
[x] No
```

RIA-4056 Upgrade “spring-boot” to 2.3.5

---

build.gradle
config/owasp/suppressions.xml

[RIA-4070](https://tools.hmcts.net/jira/browse/RIA-4070)
```
[ ] Yes
[x] No
```

RIA-4070 Upgrade guava version 30.0

---

build.gradle
charts/ia-timed-event-service/Chart.yaml

[RIA-4278](https://tools.hmcts.net/jira/browse/RIA-4278)
fix CVE and upgrade Charts
```
[ ] Yes
[x] No
```

RIA-4278 fix CVE and upgrade Charts

---

src/functionalTest/java/uk/gov/hmcts/reform/timedevent/testutils/data/CaseDataFixture.java

RIA-4363 Fixed the build issue

---

src/main/java/uk/gov/hmcts/reform/timedevent/domain/entities/ccd/Event.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/timedevent/domain/entities/ccd/EventTest.java

RIA-4437
POC for payments duplication
```
[ ] Yes
[x] No
```

RIA-4437 POC for payments duplication

---

src/main/java/uk/gov/hmcts/reform/timedevent/domain/entities/ccd/Event.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/timedevent/domain/entities/ccd/EventTest.java

[RIA-4437](RIA-4437)
Additional rollback events for payment timeout (infrastructure error)
```
[ ] Yes
[x] No
```

Ria 4437 payment timeout rollback

---

charts/ia-timed-event-service/Chart.yaml

N/A
Charts upgrade 3.6.0
```
[ ] Yes
[x] No
```

Charts upgrade 3.6.0

---

infrastructure/state.tf
src/functionalTest/java/uk/gov/hmcts/reform/timedevent/scenarios/RequestHearingRequirementsFunctionTest.java
src/functionalTest/java/uk/gov/hmcts/reform/timedevent/testutils/data/CaseDataFixture.java
src/main/java/uk/gov/hmcts/reform/timedevent/domain/entities/ccd/DynamicList.java
src/main/java/uk/gov/hmcts/reform/timedevent/domain/entities/ccd/Value.java
src/test/java/uk/gov/hmcts/reform/timedevent/domain/entities/ccd/DynamicListTest.java
src/test/java/uk/gov/hmcts/reform/timedevent/domain/entities/ccd/ValueTest.java

Pipeline and functional test fix

---

charts/ia-timed-event-service/Chart.yaml

https://tools.hmcts.net/jira/browse/RIA-5503
```
[ ] Yes
[x] No
```

RIA-5503: Upgrade base helm charts to latest

---

config/owasp/suppressions.xml

RIA-5664 suppress databind warning until a stable fix is deployed

---

charts/ia-timed-event-service/Chart.yaml
charts/ia-timed-event-service/values.preview.template.yaml
charts/ia-timed-event-service/values.yaml
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/timedevent/domain/entities/ccd/Event.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/timedevent/domain/entities/ccd/EventTest.java

Ria 5792 timed event svc remission rej spike

---

src/main/resources/application.yaml

RIA-5798: Added event access to ia-system usert

---

src/functionalTest/java/uk/gov/hmcts/reform/timedevent/scenarios/EndAppealAutomaticallyFunctionTest.java
src/functionalTest/java/uk/gov/hmcts/reform/timedevent/testutils/data/CaseDataFixture.java
src/main/resources/application.yaml

Ria 5727 endappeal functional tests

---

config/owasp/suppressions.xml
src/main/resources/application.yaml

[RIA-6594](https://tools.hmcts.net/jira/browse/RIA-6594)
[RIA-6572](https://tools.hmcts.net/jira/browse/RIA-6572)
- Allow citizen role to use `endAppealAutomatically` to schedule the triggering of the `endAppeal` event when conditions are right (remissions, appeal type etc.)
```
[ ] Yes
[x] No
```

RIA-6572 RIA-6594 Allow endAppealAutomatically for citizen role

---

Jenkinsfile_CNP
Jenkinsfile_parameterized
build.gradle
charts/ia-timed-event-service/Chart.yaml
config/owasp/suppressions.xml

To upgrade java chart version
To upgrade java chart version
```
[ ] Yes
[ X] No
```

To upgrade java chart version

---

charts/ia-timed-event-service/Chart.yaml
config/owasp/suppressions.xml

to revise chart version
to revise chart version
```
[ ] Yes
[X ] No
```

to revise chart version

---

config/owasp/suppressions.xml
src/main/resources/application.yaml

This is merge AIP payment changes to master
This is merge AIP payment changes to master
```
[ ] Yes
[ X] No
```

maSter <- AIP Payment : DO NOT MERGE

---

config/owasp/suppressions.xml

…atabind to end of september
https://tools.hmcts.net/jira/browse/RIA-5679
Updated suppression for jackson-databind CVE-2023-35116
```
[ ] Yes
[x] No
```

RIA-5679 - update supressions

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RIA-7386
Removed suppression of CVE-2023-41080, added dependency for it with specific version without vulnerability
```
[ ] Yes
[X] No
```

RIA-5679 Changing suppression to solved dependency

---

build.gradle

DIAC-53 fix

---

.github/workflows/swagger.yml
build.gradle

RIA-1234 fix swagger workflow

---

.github/workflows/swagger.yml
build.gradle

DIAC-53 swagger fix

---

infrastructure/main.tf

Update postgres flexible server db module name

DIAC-113 Update postgres flexible server db module name

---

charts/ia-timed-event-service/Chart.yaml
infrastructure/main.tf
infrastructure/state.tf
infrastructure/variables.tf

Add terraform module for timed-event-service db flexible server

DIAC-113 timed event service db 15 terraform module

---

charts/ia-timed-event-service/Chart.yaml
infrastructure/main.tf
infrastructure/state.tf
infrastructure/variables.tf

Add terraform module for timed-event-service db flexible server

DIAC-113 Add terraform module for timed-event-service db flexible server in ITHC

---

charts/ia-timed-event-service/Chart.yaml
infrastructure/main.tf
infrastructure/state.tf
infrastructure/variables.tf

Add terraform module for timed-event-service db flexible server

DIAC-113 Add terraform module for timed-event-service db flexible server

---

Jenkinsfile_nightly
build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/timedevent/testutils/SpringBootIntegrationTest.java

Jira link (if applicable)
https://tools.hmcts.net/jira/browse/DIAC-118

DIAC-70 adding smoke, unit, integration testing and reports to nightly build

---

infrastructure/main.tf
infrastructure/variables.tf

Delete ia-timed-event-service postgres flexible server in demo

DIAC-113 delete ia-timed-event-service postgres flexible server in demo

---

infrastructure/main.tf
infrastructure/variables.tf

Delete ia-timed-event-service postgres flexible server in perftest

DIAC-113 delete ia-timed-event-service postgres flexible server in perftest

---

infrastructure/main.tf
infrastructure/variables.tf

Delete ia-timed-event-service postgres flexible server in ITHC

DIAC-113 delete ia-timed-event-service postgres flexible server in ITHC

---

infrastructure/main.tf

Add ia-timed-event-service postgres flexible server in Demo

DIAC-113 Add ia-timed-event-service postgres flexible server in Demo

---

infrastructure/main.tf

Add ia-timed-event-service postgres flexible server in Perftest

DIAC-113 Add ia-timed-event-service postgres flexible server in Perftest

---

infrastructure/main.tf

Add ia-timed-event-service postgres flexible server in ITHC

DIAC-113 Add ia-timed-event-service postgres flexible server in ITHC

---

.github/workflows/pr-title-validation.yml
build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DIAC-173

DIAC-173 dependency fixes and pr validation update

---

.github/renovate.json
build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DIAC-2
Updating renovate JSON

Updating renovate JSON

---

charts/ia-timed-event-service/Chart.yaml
charts/ia-timed-event-service/values.yaml
src/main/resources/bootstrap.yaml

Use postgres database version 15

DIAC-113 Switch to Postgres database v15

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/timedevent/scenarios/EndAppealAutomaticallyFunctionTest.java
src/functionalTest/java/uk/gov/hmcts/reform/timedevent/scenarios/RequestHearingRequirementsFunctionTest.java

DIAC-123 making functionals less flakey

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/timedevent/testutils/data/IdamAuthProvider.java
src/integrationTest/java/uk/gov/hmcts/reform/timedevent/infrastructure/controllers/RetryLogicIntegrationTest.java

DIAC-123 Fixing test flakiness

---

build.gradle

https://tools.hmcts.net/jira/browse/DIAC-228

DIAC-228 nightly fix

---

build.gradle
charts/ia-timed-event-service/Chart.yaml
charts/ia-timed-event-service/values.yaml
config/owasp/suppressions.xml
infrastructure/main.tf

https://tools.hmcts.net/jira/browse/DIAC-158

DIAC-158 - decommission postgres 11

---

infrastructure/main.tf

DIAC-158 decommission postgres test

---

build.gradle

https://tools.hmcts.net/jira/browse/DIAC-354

DIAC-354 fixing dependencies

---

src/main/java/uk/gov/hmcts/reform/timedevent/infrastructure/domain/entities/ccd/Event.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/timedevent/domain/entities/ccd/EventTest.java

Jira link (if applicable)
https://tools.hmcts.net/jira/browse/RIA-8064
Change description
Telephony Payment - Payment reminder - LR Notification (Email) -Update

RIA-8064 Timed_event_permissions

---

src/functionalTest/resources/templates/minimal-appeal-started.json

RIA-0000 Update to fix test data on functional test scenarios
RIA-0000 Update to fix test data on functional test scenarios

RIA-0000 Update to fix test data on functional test scenarios

---

charts/ia-timed-event-service/Chart.yaml

https://tools.hmcts.net/jira/browse/DIAC-401

DIAC-401 bump chart version

---

charts/ia-timed-event-service/Chart.yaml
infrastructure/state.tf

DIAC-401 Bump terraform azurerm provider version

DIAC-401 update charts

---

build.gradle
charts/ia-timed-event-service/Chart.yaml
charts/ia-timed-event-service/values.preview.template.yaml
charts/ia-timed-event-service/values.yaml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DIAC-540
remove deprecated config and add configtree

DIAC-540 - remove deprecated config and add configtree

---

src/main/java/uk/gov/hmcts/reform/timedevent/infrastructure/domain/entities/ccd/Event.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/timedevent/domain/entities/ccd/EventTest.java

https://tools.hmcts.net/jira/browse/RIA-8366
- New timed event added 'sendPaymentReminderNotification' and given authorisations
- Unit test updated

RIA-8366 Adding new event 'Send payment reminder notification' with authorisations

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DIAC-835

DIAC-835 Add role event access entries for saveNotificationsToData event

---

infrastructure/main.tf

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

DIAC-688 - remove plpgsql as its default and shouldnt be here

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/timedevent/testutils/FunctionalSpringContext.java

See [DIAC-1418](https://tools.hmcts.net/jira/browse/DIAC-1418)
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?

DIAC-1418 removing unnused hystrix

---

build.gradle
config/owasp/suppressions.xml

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?

DIAC-000 Dependency check fix
